// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error ListQueues, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.MSTestExtensionsTestClassTests.#UnitTestInterceptionWithNoCustomAttributes()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.TestTransactionAttributeTests.#UnitTestInterceptionWithTestTransaction()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Console.WriteLine(System.String)", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.TestTransactionAttributeTests.#UnitTestInterceptionWithTestTransactionCommitted()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "TestInterceptionWithNoAttributes", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.MSTestExtensionsTestClassTests.#UnitTestInterceptionWithNoCustomAttributes()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "TestInterceptionWithTestTransaction", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.TestTransactionAttributeTests.#UnitTestInterceptionWithTestTransactionCommitted()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "TestInterceptionWithTestTransaction", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.TestTransactionAttributeTests.#UnitTestInterceptionWithTestTransaction()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.DeploymentItemWithLongPathAttributeTests.#DeploymentItemWithLongPath_UsingLongDirectoryNameAsSource_Succeeds()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.DeploymentItemWithLongPathAttributeTests.#DeploymentItemWithLongPath_UsingLongDirectoryNameAsSourceAndLongOutputDirectoryName_Succeeds()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.DeploymentItemWithLongPathAttributeTests.#DeploymentItemWithLongPath_UsingLongFileNameAsSource_Succeeds()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.DeploymentItemWithLongPathAttributeTests.#DeploymentItemWithLongPath_UsingLongFileNameAsSourceAndLongOutputDirectoryName_Succeeds()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.DeploymentItemWithLongPathAttributeTests.#DeploymentItemWithLongPath_UsingShortDirectoryNameAsSource_Succeeds()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.DeploymentItemWithLongPathAttributeTests.#DeploymentItemWithLongPath_UsingShortDirectoryNameAsSourceAndShortOutputDirectoryName_Succeeds()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.DeploymentItemWithLongPathAttributeTests.#DeploymentItemWithLongPath_UsingShortFileNameAsSource_Succeeds()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.MSTestExtensions.Tests.DeploymentItemWithLongPathAttributeTests.#DeploymentItemWithLongPath_UsingShortFileNameAsSourceAndShortOutputDirectoryName_Succeeds()")]
